# Generated by Django 3.0.5 on 2020-05-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('who_pay', models.CharField(max_length=254)),
                ('public_private', models.CharField(max_length=30)),
                ('inputer', models.CharField(max_length=254)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('man_rent_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('women_rent_fee', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
